name: 'tbdocs'
description: 'Provide a description here'
author: 'TBD54566975'

inputs:
  entry_points:
    description:
      'List of each project you want to run tbdocs against (YAML format)'
    required: false
    default: |
      - file: src/index.ts
        docsReporter: api-extractor
        docsGenerator: typedoc-markdown

  # entry point yaml fields:
  # file: path to the entry point file
  # docsReporter: name of the docs reporter tool
  # docsReporterIgnore: list of errors to ignore `extractor:ae-missing-release-tag`, `docs:tsdoc-param-tag-with-invalid-name`, etc.
  # docsGenerator: name of the docs generator tool
  # readmeFile: path to the readme file (eg README.md)
  # targetRepoPath: path to push the generated docs in the target repo (see docs_target_owner_repo below)

  token:
    description: 'Token used to submit comments summary and open PRs'
    required: false

  # to allow opening PRs across different repos we need an authorized bot app
  # you could also use a user PAT in the above token field, but the generated
  # comments/PRs will be sent from the user
  bot_app_id:
    description: 'Bot app id'
    required: false
  bot_app_private_key:
    description: 'Bot app private key (pem format)'
    required: false
  bot_app_installation_id:
    description: 'Bot app installation id'
    required: false

  # reporter params
  report_changed_scope_only:
    description: 'Should it report only changed scope?'
    required: false
    default: 'false'
  fail_on_error:
    description: 'Should it fail on report errors?'
    required: false
    default: 'true'
  fail_on_warnings:
    description: 'Should it fail on report warnings?'
    required: false
    default: 'false'

  group_docs:
    description:
      'Should it group the generated docs files in the `.tbdocs/docs` folder?'
    required: false
    default: 'false'

  # generated docs params, if you want to open a PR to a different repo with the generated docs
  docs_target_owner_repo:
    description:
      'Target owner/repo for the generated docs PR (skips opening a PR if empty)'
    required: false
  docs_target_branch:
    description: 'Target branch for the generated docs PR'
    required: false
    default: 'main'
  docs_target_pr_base_branch:
    description: 'Target base branch for the generated docs PR'
    required: false
    default: 'main'

  # generator params
  docs_generator:
    description:
      'Name of the docs generator tool (skips docs generation if empty)'
    required: false
outputs:
  report:
    description: 'Generated docs report JSON object'

runs:
  using: 'docker'
  image: 'Dockerfile'
