name: 'tbdocs'
description: 'Provide a description here'
author: 'TBD54566975'

inputs:
  docs_report:
    description: 'What is the docs report tool?'
    required: true
    default: 'api-extractor'
  fail_on_error:
    description: 'Should it fail on error?'
    required: false
    default: 'false'
  api_extractor_json_path:
    description: 'Path to the api-extractor.json file'
    required: false
    default: ''

outputs:
  report:
    description: 'Generated docs report JSON object'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docs_report }}
    - ${{ inputs.fail_on_error }}

# runs:
#   using: 'composite'
#   steps:
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 20
#         cache: 'npm'

#     - name: Install API Extractor
#       shell: bash
#       run: npm ci
      
#     - name: Run Docs Report
#       shell: bash
#       run: node scripts/main.js
      
