name: 'tbdocs'
description: 'Provide a description here'
author: 'TBD54566975'

inputs:
  docs_report:
    description: 'What is the docs report tool?'
    required: true
    default: 'api-extractor'
  fail_on_error:
    description: 'Should it fail on error?'
    required: false
    default: 'false'

outputs:
  report:
    description: 'Generated docs report JSON object'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - name: Install API Extractor
      shell: bash
      run: npm install -g @microsoft/api-extractor
      
    - name: Run Docs Report
      shell: bash
      run: node dist/main.js
      
