name: 'tbdocs'
description: 'Provide a description here'
author: 'TBD54566975'

# Define your inputs here.
inputs:
  docs_report:
    description: 'What is the docs report tool?'
    required: true
    default: 'api-extractor'
  fail_on_error:
    description: 'Should it fail on error?'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  report:
    description: 'Generated docs report JSON object'

runs:
  using: "composite"
  steps:
  - run: npm install -g @microsoft/api-extractor
  - run: node dist/main.js

