name: 'tbdocs'
description: 'Provide a description here'
author: 'TBD54566975'

inputs:
  docs_report:
    description: 'What is the docs report tool?'
    required: true
    default: 'api-extractor'
  project_path:
    description: 'Path to the project root'
    required: false
    default: '.'
  token:
    description: 'Token used to submit comments summary and open PRs'
    required: false
  fail_on_error:
    description: 'Should it fail on error?'
    required: false
    default: 'false'
  api_extractor_json_path:
    description: 'Path to the api-extractor.json file'
    required: false
    default: ''

outputs:
  report:
    description: 'Generated docs report JSON object'

runs:
  using: 'docker'
  image: 'Dockerfile'
