name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: Test Action Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Build
        id: npm-build
        run: npm run bundle

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Build Example
        id: example-npm-build
        run: cd examples/foo && npm ci && npm run build && cd ../..

      - name: TBDocs Reporter
        id: tbdocs-reporter
        uses: ./
        with:
          fail_on_error: true
          fail_on_warnings: true
          report_changed_scope_only: false
          token: ${{ secrets.GITHUB_TOKEN }}
          entry_points: |
            - file: src/index.ts
              docsReporter: api-extractor
              docsGenerator: typedoc-markdown
            - file: examples/foo/index.ts
              docsReporter: api-extractor
              docsGenerator: typedoc-markdown

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tbdocs-reporter-output
          path: ./.tbdocs
