name: TBDocs Reporter

on:
  workflow_dispatch:

  workflow_run:
    workflows: ['Continuous Integration']
    types:
      - completed

jobs:
  test-action:
    name: Test Action Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build
        id: npm-build
        run: npm run bundle

      - name: Build Example
        id: example-npm-build
        run: cd examples/foo && npm ci && npm run build && cd ../..

      - name: TBDocs Reporter
        id: tbdocs-reporter
        uses: ./
        with:
          fail_on_error: true
          fail_on_warnings: true
          report_changed_scope_only: false
          bot_app_id: ${{ secrets.BOT_APP_ID }}
          bot_app_private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          bot_app_installation_id: ${{ secrets.BOT_APP_INSTALLATION_ID }}
          entry_points: |
            - file: src/index.ts
              docsReporter: api-extractor
              docsGenerator: typedoc-markdown
            - file: examples/foo/index.ts
              docsReporter: api-extractor
              docsGenerator: typedoc-markdown

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tbdocs-reporter-output
          path: ./.tbdocs
